   language: python
   python:
      - "3.5"
   install:
      - pip install -r travis/requirements.txt
      - pip install coveralls
   script:
      - python3 test_rpn.py
      - coverage run test_rpn.py
   after_success: coveralls
